{% set name = "pytmc" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/pytmc/archive/v{{ version }}.tar.gz
  sha256: e408cc34d5a56ce149cc98c1843da2f99a795586c48dc1ef7431171d5b2611fa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytmc = pytmc.bin.pytmc:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jinja2
    - lxml
    - epics-pypdb >=0.1.5

test:
  imports:
    - pytmc
  requires:
    - pytest
    - pytest-qt
    - qtpy
    - pyqt >=5

about:
  home: https://github.com/slaclab/pytmc
  doc_url: https://slaclab.github.io/pytmc/
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE
  summary: Generate EPICS IOCs and records from Beckhoff TwinCAT projects

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka
    - zllentz
    - n-wbrown
