{% set name = "pytmc" %}
{% set version = "2.6.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/pytmc/archive/v{{ version }}.tar.gz
  sha256: fa5bc209c85391e80ae0dc0a4386d4ebb7b589c0ba8eca2208c8b608224b0134

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytmc = pytmc.bin.pytmc:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jinja2
    - lxml
    - epics-pypdb >=0.1.5

test:
  imports:
    - pytmc
  requires:
    - pytest
    - pytest-qt
    - qtpy
    - pyqt >=5

about:
  home: https://github.com/slaclab/pytmc
  doc_url: https://slaclab.github.io/pytmc/
  license: SLAC Open
  license_family: Other
  license_file: LICENSE
  summary: Generate EPICS IOCs and records from Beckhoff TwinCAT projects

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka
    - zllentz
    - n-wbrown
